"""Add page numbers columns to Task and TaskLog models

Revision ID: fec035e084a2
Revises: d23ff1b674a8
Create Date: 2025-07-02 20:43:31.030734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fec035e084a2'
down_revision = 'd23ff1b674a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_page_numbers', sa.String(length=200), nullable=True))

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('log_completed_page_numbers', sa.Boolean(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('log_completed_page_numbers')

    with op.batch_alter_table('task_logs', schema=None) as batch_op:
        batch_op.drop_column('completed_page_numbers')

    # ### end Alembic commands ###
